name: Scrape BTM CSVs
required: true
default: "SPX"
risks:
description: "Riesgos separados por coma"
required: false
default: "Conservative,Intermediate,Aggressive,Ultra Aggressive"
horarios:
description: "Horarios HH:MM separados por coma"
required: false
default: "09:40,10:00,10:20,10:40,11:00,11:20,11:30,12:00,12:20,12:40,13:00,13:20,13:40,14:00,14:20,14:40,15:00"
schedule:
- cron: '30 15 * * 1-5' # 09:30 MX (UTC-06) → 15:30 UTC


env:
TZ: America/Monterrey
PLAYWRIGHT_BROWSERS_PATH: 0


permissions:
contents: write


jobs:
scrape:
runs-on: ubuntu-latest


steps:
- name: Checkout
uses: actions/checkout@v4


- name: Setup Python
uses: actions/setup-python@v5
with:
python-version: '3.11'


- name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install -r requirements.txt
python -m playwright install --with-deps chromium


- name: Run scraper
env:
BTM_EMAIL: ${{ secrets.BTM_EMAIL }}
BTM_PASSWORD: ${{ secrets.BTM_PASSWORD }}
LOGIN_URL: ${{ vars.LOGIN_URL }}
DASHBOARD_URL: ${{ vars.DASHBOARD_URL }}
run: |
SYMBOL="${{ github.event.inputs.symbol }}"
RISKS="${{ github.event.inputs.risks }}"
HORARIOS="${{ github.event.inputs.horarios }}"
SYMBOL=${SYMBOL:-SPX}
RISKS=${RISKS:-"Conservative,Intermediate,Aggressive,Ultra Aggressive"}
HORARIOS=${HORARIOS:-"09:40,10:00,10:20,10:40,11:00,11:20,11:30,12:00,12:20,12:40,13:00,13:20,13:40,14:00,14:20,14:40,15:00"}


python scraper/btm_scraper.py \
--symbol "$SYMBOL" \
--risks "$RISKS" \
--horarios "$HORARIOS"


- name: Commit & push data
run: |
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add data || true
if git diff --staged --quiet; then
echo "No hay cambios nuevos para commitear."
else
git commit -m "Data update: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
git push
fi


- name: Upload CSVs as artifact (opcional)
uses: actions/upload-artifact@v4
with:
name: csvs-${{ github.run_id }}
path: data/
